name: build-and-push-buster
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build_and_push:
    name: build and push docker image(buster)
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.5
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE="ghcr.io/${GITHUB_REPOSITORY}"
          VERSION=debug
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:8-buster-${VERSION}"
          if [ "${{ github.event_name }}" = "push" ]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:8-buster-sha-${GITHUB_SHA::8}"
          fi
          echo ::set-output name=tags::${TAGS}
      - name: setup buildx
        uses: docker/setup-buildx-action@v1.3.0
      - name: login
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          pull: true
          push: true
          file: Dockerfile.buster
          tags: ${{ steps.prep.outputs.tags }}
